name: gradient_slider
description: A slider widget, supports image thumb, track gradient and border
version: 1.3.0
homepage: https://github.com/ihsankottupadam/flutter-gradient-slider
repository: https://github.com/ihsankottupadam/flutter-gradient-slider
issue_tracker: https://github.com/ihsankottupadam/flutter-gradient-slider/issues

topics:
  - slider
  - gradient
  - image-thumb

screenshots:
  - description: 'Image thumb, default Material thumb, range slider and no thumb'
    path: screenshots/slider_modes.png


environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  lints: ^6.0.0

flutter:

