name: gradient_slider
description: A slider widget, supports image thumb, track gradient and border
version: 1.0.0
homepage: https://github.com/ihsankottupadam/flutter-gradient-slider
environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  lints: ^2.0.1

flutter:

